name: Notify Telegram on Issue + Comments

on:
  issues:
    types: [opened, closed, reopened]
  issue_comment:
    types: [created]

jobs:
  notify-telegram:
    # Permite qualquer evento de "issues" e, no caso de "issue_comment",
    # só segue se NÃO for comentário em PR.
    if: ${{ github.event_name != 'issue_comment' || github.event.issue.pull_request == null }}
    runs-on: ubuntu-latest
    permissions:
      issues: read

    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: "-1002597220683"   # opcional: mova p/ secrets
      TELEGRAM_THREAD_ID: "6"              # opcional: remova se não usar tópicos
      REPO: ${{ github.repository }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install httpx
        run: |
          python -m pip install --upgrade pip
          pip install httpx

      # Monta a mensagem e dados específicos conforme o evento
      - name: Compose Telegram message
        id: compose
        shell: bash
        run: |
          set -euo pipefail

          write_output() {
            # uso: write_output chave "valor possivelmente multilinha"
            local key="$1"; shift
            local delim="__GH_OUT_$(openssl rand -hex 8)__"
            {
              printf '%s<<%s\n' "$key" "$delim"
              cat
              printf '%s\n' "$delim"
            } >> "$GITHUB_OUTPUT"
          }

          EVENT="${{ github.event_name }}"
          ACTION="${{ github.event.action }}"

          if [ "$EVENT" = "issues" ]; then
            NUMBER='${{ github.event.issue.number }}'
            TITLE='${{ github.event.issue.title }}'
            URL='${{ github.event.issue.html_url }}'
            USER='${{ github.event.sender.login }}'
            BODY='${{ github.event.issue.body }}'

            case "$ACTION" in
              opened)   MSG="🔔 Nova issue #$NUMBER aberta por $USER: $TITLE\n$URL" ;;
              closed)   MSG="✅ Issue #$NUMBER fechada por $USER\n$URL" ;;
              reopened) MSG="♻️ Issue #$NUMBER reaberta por $USER\n$URL" ;;
              *)        MSG="ℹ️ Issue #$NUMBER atualizada por $USER: $TITLE\n$URL" ;;
            esac

            printf '%s' "$TITLE"  | write_output issue_title
            printf '%s' "$NUMBER" | write_output issue_number
            printf '%s' "$URL"    | write_output issue_url
            printf '%s' "$USER"   | write_output issue_user
            printf '%s' "$BODY"   | write_output issue_body

            # labels (como JSON simples de strings)
            jq -r '[.issue.labels[].name] | @json' "${GITHUB_EVENT_PATH}" \
              | write_output issue_labels_json || printf '[]' | write_output issue_labels_json

          elif [ "$EVENT" = "issue_comment" ]; then
            NUMBER='${{ github.event.issue.number }}'
            URL='${{ github.event.comment.html_url }}'
            USER='${{ github.event.comment.user.login }}'
            BODY_RAW='${{ github.event.comment.body }}'

            BODY_PREVIEW=$(printf "%s" "$BODY_RAW" | head -c 280)
            MSG="💬 Novo comentário na issue #$NUMBER por $USER:\n\"$BODY_PREVIEW\"\n$URL"

            printf '%s' "$USER"      | write_output comment_user
            printf '%s' "$BODY_RAW"  | write_output comment_body
            printf '%s' "$NUMBER"    | write_output issue_number
            printf '%s' "${{ github.event.issue.html_url }}" | write_output issue_url
            printf '%s' "${{ github.event.issue.title }}"    | write_output issue_title
            printf '%s' "${{ github.event.issue.body }}"     | write_output issue_body

            jq -r '[.issue.labels[].name] | @json' "${GITHUB_EVENT_PATH}" \
              | write_output issue_labels_json || printf '[]' | write_output issue_labels_json
          fi

          printf "%b" "$MSG" | write_output message

      - name: Send Telegram (via script .py)
        env:
          TELEGRAM_BOT_TOKEN: ${{ env.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ env.TELEGRAM_CHAT_ID }}
          TELEGRAM_THREAD_ID: ${{ env.TELEGRAM_THREAD_ID }}

          MESSAGE: ${{ steps.compose.outputs.message }}

          # Dados da issue (sempre disponíveis)
          ISSUE_TITLE: ${{ steps.compose.outputs.issue_title }}
          ISSUE_NUMBER: ${{ steps.compose.outputs.issue_number }}
          ISSUE_URL:    ${{ steps.compose.outputs.issue_url }}
          ISSUE_USER:   ${{ steps.compose.outputs.issue_user }}
          ISSUE_BODY:   ${{ steps.compose.outputs.issue_body }}

          # Dados de comentário (presentes só no evento issue_comment)
          COMMENT_USER: ${{ steps.compose.outputs.comment_user }}
          COMMENT_BODY: ${{ steps.compose.outputs.comment_body }}

          # Metadados úteis
          EVENT_NAME: ${{ github.event_name }}
          EVENT_ACTION: ${{ github.event.action }}
          REPO: ${{ env.REPO }}
          APPEND_LABELS_TO_MESSAGE: "true"
        run: |
          python automations/telegram/issue.py
