name: Notify Telegram on Issue Opened

on:
  issues:
    types: [opened, closed, reopened, assigned, milestoned, labeled]

jobs:
  notify-telegram:
    runs-on: ubuntu-latest
    permissions:
      issues: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install httpx
        run: |
          python -m pip install --upgrade pip
          pip install httpx

      - name: Call telegram script.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
          ISSUE_USER: ${{ github.event.issue.user.login }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          REPO: ${{ github.repository }}
          ISSUE_LABELS: ${{ github.event.issue.labels.*.name ) }}

        run: |
          python automations/telegram/issue.py
